language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: fNaTLbK3gFtCbp44ss1Av04lpE3b8ARU6Pe0w3X7fUGJ35EKIgk8y/2MVl16BKIvoSUC0Bc04KvGZsIkVdHZw6HRNOwDWq1TDqUSmE+khc3FJ6U3DLDO/Fx84gxXvHH5Get2uSDIf0iOmf0uiKkglfAgaRIAP/fxEptQ7+tyChs=
  - secure: Ef7w6QuRL8V1A80hp1FLJekOrXfO/85+OAJxQFRh67OuS7i1jbCVJ9JZQiOK+0q7HJxpGtkg5Ve7gXE3X/dNlyNOSnFfohHiMMndI5sWzSi5dPGEiiKEZ5mXjcjMp3sggb72RjvX9KmiloJ99QEzNQwgJ5ppcEQXT9i3d6UI2Rc=
